<?php
declare(strict_types=1);
namespace DersRotasi\Pomodoro;
use PDO;
use RuntimeException;
use Throwable;

final class PomodoroRepository {
    public const ACTIVE_PRESENCE_SECONDS = 45;
    public const EMPTY_ROOM_GRACE_SECONDS = 90;
    public function __construct(private readonly PDO $pdo) {}
    private function uid(string $uid): string { if ($uid === '' || strlen($uid) > 128) throw new RuntimeException('Oturum geçersiz.', 401); return $uid; }
    private function rate(string $uid, string $action, int $limit, int $window = 60): void {
        $key = hash('sha256', $action.':'.$uid); $s=$this->pdo->prepare('SELECT attempts,window_started_at FROM pomodoro_rate_limits WHERE action_key=:k'); $s->execute(['k'=>$key]); $r=$s->fetch(PDO::FETCH_ASSOC);
        if (!$r || strtotime($r['window_started_at']) <= time()-$window) $this->pdo->prepare('INSERT INTO pomodoro_rate_limits(action_key,attempts,window_started_at) VALUES(:k,1,NOW()) ON DUPLICATE KEY UPDATE attempts=1,window_started_at=NOW()')->execute(['k'=>$key]);
        elseif ((int)$r['attempts'] >= $limit) throw new RuntimeException('Çok fazla istek gönderdin. Lütfen biraz bekle.',429);
        else $this->pdo->prepare('UPDATE pomodoro_rate_limits SET attempts=attempts+1 WHERE action_key=:k')->execute(['k'=>$key]);
    }
    public function list(string $uid, string $filter): array {
        $this->reconcileRooms();
        $order=$filter==='popular'?'member_count DESC': 'r.created_at DESC'; $where=in_array($filter,['TYT','AYT'],true)?' AND r.category=:category':'';
        $active=self::ACTIVE_PRESENCE_SECONDS;
        $s=$this->pdo->prepare("SELECT r.*,COUNT(CASE WHEN m.status='active' AND m.last_seen_at>DATE_SUB(NOW(),INTERVAL {$active} SECOND) THEN 1 END) member_count,NOW(3) server_now FROM pomodoro_rooms r LEFT JOIN pomodoro_room_members m ON m.room_id=r.id WHERE r.status='active' AND r.visibility='public' {$where} GROUP BY r.id ORDER BY {$order} LIMIT 60"); $s->execute($where?['category'=>$filter]:[]); return array_map([$this,'roomRow'],$s->fetchAll(PDO::FETCH_ASSOC));
    }
    public function create(string $uid,array $p): array {
        $this->rate($uid,'create',5,3600); $name=trim((string)($p['name']??'')); $cat=trim((string)($p['category']??'')); $desc=trim((string)($p['description']??'')); $vis=(string)($p['visibility']??'public'); $work=(int)($p['work_minutes']??25); $break=(int)($p['break_minutes']??5); $max=(int)($p['max_members']??12); $protected=(bool)($p['password_protected']??false); $password=(string)($p['password']??'');
        if ($name===''||mb_strlen($name)>80||$cat===''||mb_strlen($cat)>40||mb_strlen($desc)>300||!in_array($vis,['public','private'],true)||$work<5||$work>180||$break<1||$break>60||$max<2||$max>50||($protected&&(strlen($password)<4||strlen($password)>64))) throw new RuntimeException('Oda bilgileri geçersiz.',422);
        try {
            $this->pdo->beginTransaction();
            $s=$this->pdo->prepare('INSERT INTO pomodoro_rooms(owner_uid,name,description,category,visibility,room_code_hash,work_minutes,break_minutes,voice_enabled,music_enabled,max_members) VALUES(:u,:n,:d,:c,:v,:h,:w,:b,:voice,:music,:max)');
            $s->execute(['u'=>$this->uid($uid),'n'=>$name,'d'=>$desc,'c'=>$cat,'v'=>$vis,'h'=>$protected?password_hash($password,PASSWORD_DEFAULT):null,'w'=>$work,'b'=>$break,'voice'=>!empty($p['voice_enabled'])?1:0,'music'=>!empty($p['music_enabled'])?1:0,'max'=>$max]);
            $id=(int)$this->pdo->lastInsertId();
            $this->upsertMember($id,$uid,'owner');
            $this->pdo->prepare('INSERT INTO pomodoro_sessions(room_id,user_uid) VALUES(:r,:u)')->execute(['r'=>$id,'u'=>$uid]);
            $this->pdo->commit();
        } catch (Throwable $exception) {
            if ($this->pdo->inTransaction()) $this->pdo->rollBack();
            throw $exception;
        }
        return $this->get($uid,$id);
    }
    public function join(string $uid,int $id,string $password=''): array { $this->rate($uid,'join',20); $r=$this->raw($id); if($r['room_code_hash']!==null&&!password_verify($password,(string)$r['room_code_hash'])) throw new RuntimeException('Oda şifresi yanlış.',403); $active=self::ACTIVE_PRESENCE_SECONDS; $count=(int)$this->pdo->query("SELECT COUNT(*) FROM pomodoro_room_members WHERE room_id={$id} AND status='active' AND last_seen_at>DATE_SUB(NOW(),INTERVAL {$active} SECOND)")->fetchColumn(); if($count >= (int)$r['max_members']) throw new RuntimeException('Oda kapasitesi dolu.',409); $this->upsertMember($id,$uid,$r['owner_uid']===$uid?'owner':'member'); $this->pdo->prepare('INSERT INTO pomodoro_sessions(room_id,user_uid) VALUES(:r,:u)')->execute(['r'=>$id,'u'=>$uid]); return $this->get($uid,$id); }
    public function heartbeat(string $uid,int $id,bool $mic): void { $this->assertMember($id,$uid); $this->account($id,$uid); $this->pdo->prepare('UPDATE pomodoro_room_members SET last_seen_at=NOW(),microphone_enabled=:m WHERE room_id=:r AND user_uid=:u')->execute(['m'=>$mic?1:0,'r'=>$id,'u'=>$uid]); }
    public function leave(string $uid,int $id): void { $this->account($id,$uid); $room=$this->raw($id); $this->pdo->prepare("UPDATE pomodoro_room_members SET status='left',microphone_enabled=0 WHERE room_id=:r AND user_uid=:u")->execute(['r'=>$id,'u'=>$uid]); $this->pdo->prepare('UPDATE pomodoro_sessions SET ended_at=NOW() WHERE room_id=:r AND user_uid=:u AND ended_at IS NULL')->execute(['r'=>$id,'u'=>$uid]); if($room['owner_uid']===$uid)$this->transferOwner($id,$uid); }
    public function get(string $uid,int $id): array { $this->reconcileRooms(); $this->raw($id); $this->assertMember($id,$uid); $this->advance($id); $r=$this->raw($id); $active=self::ACTIVE_PRESENCE_SECONDS; $s=$this->pdo->prepare("SELECT m.*,COALESCE(NULLIF(p.username,''),'Öğrenci') username,p.profile_photo_path FROM pomodoro_room_members m LEFT JOIN user_profiles p ON p.firebase_uid=m.user_uid WHERE m.room_id=:r AND m.status='active' AND m.last_seen_at>DATE_SUB(NOW(),INTERVAL {$active} SECOND) ORDER BY m.role='owner' DESC,m.joined_at"); $s->execute(['r'=>$id]); $members=array_map(fn($m)=>['user_key'=>$m['user_uid'],'username'=>$m['username'],'profile_photo_url'=>$m['profile_photo_path'],'role'=>$m['role'],'microphone_enabled'=>(bool)$m['microphone_enabled']],$s->fetchAll(PDO::FETCH_ASSOC)); $q=$this->pdo->prepare("SELECT q.*,COALESCE(NULLIF(p.username,''),'Öğrenci') added_by FROM pomodoro_music_queue q LEFT JOIN user_profiles p ON p.firebase_uid=q.added_by_uid WHERE q.room_id=:r ORDER BY q.position,q.id"); $q->execute(['r'=>$id]); return [...$this->roomRow($r),'is_owner'=>$r['owner_uid']===$uid,'members'=>$members,'member_count'=>count($members),'music_queue'=>$q->fetchAll(PDO::FETCH_ASSOC)]; }
    public function timer(string $uid,int $id,array $p): array { $r=$this->owner($id,$uid); $a=$p['action']??''; if($a==='start'||$a==='resume'){ $phase=$a==='resume'&&$r['phase_before_pause']?$r['phase_before_pause']:'work'; $seconds=$a==='resume'?(int)$r['remaining_seconds']:(int)$r['work_minutes']*60; $this->pdo->prepare('UPDATE pomodoro_rooms SET current_phase=:p,phase_started_at=NOW(3),phase_ends_at=DATE_ADD(NOW(3),INTERVAL :s SECOND),remaining_seconds=NULL WHERE id=:id')->execute(['p'=>$phase,'s'=>$seconds,'id'=>$id]); } elseif($a==='pause'){ $this->pdo->prepare("UPDATE pomodoro_rooms SET phase_before_pause=current_phase,current_phase='paused',remaining_seconds=GREATEST(0,TIMESTAMPDIFF(SECOND,NOW(3),phase_ends_at)),phase_ends_at=NULL WHERE id=:id AND current_phase IN('work','break')")->execute(['id'=>$id]); } elseif($a==='next'){ $this->next($id,$r); } elseif($a==='durations'){ $w=(int)($p['work_minutes']??0);$b=(int)($p['break_minutes']??0);if($w<5||$w>180||$b<1||$b>60)throw new RuntimeException('Süreler geçersiz.',422);$this->pdo->prepare('UPDATE pomodoro_rooms SET work_minutes=:w,break_minutes=:b WHERE id=:id')->execute(['w'=>$w,'b'=>$b,'id'=>$id]); } else throw new RuntimeException('Sayaç işlemi geçersiz.',422); return $this->get($uid,$id); }
    private function next(int $id,array $r):void { $phase=$r['current_phase']==='work'?'break':'work';$seconds=(int)($phase==='work'?$r['work_minutes']:$r['break_minutes'])*60;$cycle=(int)$r['cycle_number']+($phase==='work'?1:0);$this->pdo->prepare('UPDATE pomodoro_rooms SET current_phase=:p,phase_started_at=NOW(3),phase_ends_at=DATE_ADD(NOW(3),INTERVAL :s SECOND),cycle_number=:c WHERE id=:id')->execute(['p'=>$phase,'s'=>$seconds,'c'=>$cycle,'id'=>$id]); }
    private function advance(int $id):void { $r=$this->raw($id);if(in_array($r['current_phase'],['work','break'],true)&&$r['phase_ends_at']&&strtotime($r['phase_ends_at'])<=time())$this->next($id,$r); }
    public function addMusic(string $uid,int $id,array $p):void { $this->assertMember($id,$uid);$r=$this->raw($id);if(!$r['music_enabled'])throw new RuntimeException('Müzik bu odada kapalı.',403);[$provider,$external]=$this->musicUrl((string)($p['external_url']??''));$pos=(int)$this->pdo->query("SELECT COALESCE(MAX(position),0)+1 FROM pomodoro_music_queue WHERE room_id={$id}")->fetchColumn();$title=mb_substr(trim((string)($p['title']??'')),0,160);$this->pdo->prepare('INSERT INTO pomodoro_music_queue(room_id,provider,external_url,external_id,title,added_by_uid,position) VALUES(:r,:p,:url,:e,:t,:u,:pos)')->execute(['r'=>$id,'p'=>$provider,'url'=>$external,'e'=>hash('sha256',$external),'t'=>$title,'u'=>$uid,'pos'=>$pos]); }
    private function musicUrl(string $value):array { $url=filter_var($value,FILTER_VALIDATE_URL);$host=$url?strtolower((string)parse_url($url,PHP_URL_HOST)):'';$provider=in_array($host,['youtube.com','www.youtube.com','youtu.be'],true)?'youtube':($host==='open.spotify.com'?'spotify':null);if(!$provider||parse_url($url,PHP_URL_SCHEME)!=='https')throw new RuntimeException('Yalnızca HTTPS YouTube ve Spotify bağlantıları desteklenir.',422);return[$provider,$url]; }
    public function musicAction(string $uid,int $id,string $a):void { $this->owner($id,$uid);if($a==='clear')$this->pdo->prepare('DELETE FROM pomodoro_music_queue WHERE room_id=:r')->execute(['r'=>$id]);elseif($a==='skip')$this->pdo->prepare('DELETE FROM pomodoro_music_queue WHERE room_id=:r ORDER BY position,id LIMIT 1')->execute(['r'=>$id]);else throw new RuntimeException('Müzik işlemi geçersiz.',422); }
    public function signal(string $uid,int $id,array $p):void { $this->rate($uid,'signal',120);$this->assertMember($id,$uid);$type=$p['signal_type']??'';$to=(string)($p['recipient_uid']??'');if(!in_array($type,['offer','answer','ice'],true)||!is_array($p['payload']??null)||strlen(json_encode($p['payload']))>12000)throw new RuntimeException('Sinyal geçersiz.',422);$this->assertMember($id,$to);$this->pdo->prepare('INSERT INTO pomodoro_signals(room_id,sender_uid,recipient_uid,signal_type,payload) VALUES(:r,:s,:to,:t,:p)')->execute(['r'=>$id,'s'=>$uid,'to'=>$to,'t'=>$type,'p'=>json_encode($p['payload'])]); }
    public function signals(string $uid,int $id,int $after):array { $this->assertMember($id,$uid);$s=$this->pdo->prepare('SELECT id,sender_uid,signal_type,payload FROM pomodoro_signals WHERE room_id=:r AND recipient_uid=:u AND id>:a ORDER BY id LIMIT 100');$s->execute(['r'=>$id,'u'=>$uid,'a'=>$after]);return array_map(fn($x)=>[...$x,'id'=>(int)$x['id'],'payload'=>json_decode($x['payload'],true)],$s->fetchAll(PDO::FETCH_ASSOC)); }
    public function moderate(string $uid,int $id,array $p):void { $action=$p['action']??'';$target=(string)($p['target_uid']??'');if($action==='report'){ $this->rate($uid,'report',5,3600);$this->assertMember($id,$uid);$reason=mb_substr(trim((string)($p['reason']??'')),0,200);if($reason==='')throw new RuntimeException('Şikâyet nedeni gerekli.',422);$this->pdo->prepare('INSERT INTO pomodoro_reports(room_id,reporter_uid,reported_uid,reason) VALUES(:r,:u,:t,:why)')->execute(['r'=>$id,'u'=>$uid,'t'=>$target,'why'=>$reason]);return;} $this->owner($id,$uid);if(!in_array($action,['kick','block'],true))throw new RuntimeException('Moderasyon işlemi geçersiz.',422);$this->pdo->prepare("UPDATE pomodoro_room_members SET status=:s WHERE room_id=:r AND user_uid=:u AND role<>'owner'")->execute(['s'=>$action==='block'?'blocked':'kicked','r'=>$id,'u'=>$target]); }
    public function stats(string $uid):array { $s=$this->pdo->prepare("SELECT COALESCE(SUM(CASE WHEN started_at>=CURDATE() THEN focused_seconds ELSE 0 END),0) today_seconds,COALESCE(SUM(CASE WHEN started_at>=DATE_SUB(CURDATE(),INTERVAL WEEKDAY(CURDATE()) DAY) THEN focused_seconds ELSE 0 END),0) week_seconds,COALESCE(SUM(completed_cycles),0) completed_cycles FROM pomodoro_sessions WHERE user_uid=:u");$s->execute(['u'=>$uid]);return array_map('intval',$s->fetch(PDO::FETCH_ASSOC)); }
    private function account(int $id,string $uid):void { $r=$this->raw($id);if($r['current_phase']==='work')$this->pdo->prepare('UPDATE pomodoro_sessions SET focused_seconds=focused_seconds+LEAST(30,GREATEST(0,TIMESTAMPDIFF(SECOND,last_accounted_at,NOW()))),last_accounted_at=NOW() WHERE room_id=:r AND user_uid=:u AND ended_at IS NULL')->execute(['r'=>$id,'u'=>$uid]); }
    private function upsertMember(int $id,string $uid,string $role):void {$this->pdo->prepare("INSERT INTO pomodoro_room_members(room_id,user_uid,role) VALUES(:r,:u,:role) ON DUPLICATE KEY UPDATE status=IF(status='blocked','blocked','active'),role=VALUES(role),last_seen_at=NOW()")->execute(['r'=>$id,'u'=>$uid,'role'=>$role]);$this->assertMember($id,$uid);}
    private function reconcileRooms():void { $grace=self::EMPTY_ROOM_GRACE_SECONDS; $this->pdo->exec("UPDATE pomodoro_rooms r SET status='closed' WHERE r.status='active' AND r.created_at<DATE_SUB(NOW(),INTERVAL {$grace} SECOND) AND NOT EXISTS (SELECT 1 FROM pomodoro_room_members m WHERE m.room_id=r.id AND m.status='active' AND m.last_seen_at>DATE_SUB(NOW(),INTERVAL {$grace} SECOND))"); $active=self::ACTIVE_PRESENCE_SECONDS; $s=$this->pdo->query("SELECT r.id,r.owner_uid FROM pomodoro_rooms r LEFT JOIN pomodoro_room_members o ON o.room_id=r.id AND o.user_uid=r.owner_uid WHERE r.status='active' AND (o.status<>'active' OR o.last_seen_at<=DATE_SUB(NOW(),INTERVAL {$active} SECOND))"); foreach($s->fetchAll(PDO::FETCH_ASSOC) as $room)$this->transferOwner((int)$room['id'],(string)$room['owner_uid']); }
    private function transferOwner(int $id,string $oldOwner):void { $active=self::ACTIVE_PRESENCE_SECONDS; $s=$this->pdo->prepare("SELECT user_uid FROM pomodoro_room_members WHERE room_id=:r AND user_uid<>:old AND status='active' AND last_seen_at>DATE_SUB(NOW(),INTERVAL {$active} SECOND) ORDER BY joined_at LIMIT 1");$s->execute(['r'=>$id,'old'=>$oldOwner]);$next=$s->fetchColumn();if(!$next)return;$this->pdo->beginTransaction();try{$this->pdo->prepare("UPDATE pomodoro_room_members SET role='member' WHERE room_id=:r AND user_uid=:old")->execute(['r'=>$id,'old'=>$oldOwner]);$this->pdo->prepare("UPDATE pomodoro_room_members SET role='owner' WHERE room_id=:r AND user_uid=:next")->execute(['r'=>$id,'next'=>$next]);$this->pdo->prepare('UPDATE pomodoro_rooms SET owner_uid=:next WHERE id=:r')->execute(['r'=>$id,'next'=>$next]);$this->pdo->commit();}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw$e;}}
    private function raw(int $id):array {$s=$this->pdo->prepare('SELECT *,NOW(3) server_now FROM pomodoro_rooms WHERE id=:id');$s->execute(['id'=>$id]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!$r)throw new RuntimeException('Oda bulunamadı.',404);if($r['status']!=='active')throw new RuntimeException('Bu oda artık aktif değil.',410);return$r;}
    private function assertMember(int $id,string $uid):void {$uid=$this->uid($uid);$s=$this->pdo->prepare("SELECT 1 FROM pomodoro_room_members WHERE room_id=:r AND user_uid=:u AND status='active'");$s->execute(['r'=>$id,'u'=>$uid]);if(!$s->fetchColumn())throw new RuntimeException('Bu odaya erişimin yok.',403);$this->pdo->prepare('UPDATE pomodoro_room_members SET last_seen_at=NOW() WHERE room_id=:r AND user_uid=:u')->execute(['r'=>$id,'u'=>$uid]);}
    private function owner(int $id,string $uid):array {$r=$this->raw($id);if($r['owner_uid']!==$uid)throw new RuntimeException('Bu işlem yalnızca oda sahibine açık.',403);return$r;}
    private function roomRow(array $r):array { $r['password_protected']=$r['room_code_hash']!==null;unset($r['owner_uid'],$r['room_code_hash'],$r['phase_before_pause'],$r['remaining_seconds']);foreach(['id','work_minutes','break_minutes','cycle_number','max_members','member_count'] as $k)if(isset($r[$k]))$r[$k]=(int)$r[$k];foreach(['voice_enabled','music_enabled','password_protected'] as $k)$r[$k]=(bool)$r[$k];return$r;}
}
