/* oxlint-disable react-hooks/exhaustive-deps -- peer ICE config is immutable and must not recreate connections. */
import { useCallback, useEffect, useRef, useState } from 'react'
import { getSignals, sendSignal } from '../api/pomodoroApi'

export function usePomodoroVoice({ user, roomId, members, enabled, canSpeak = false, muteAt = 0 }) {
  const [status, setStatus] = useState('idle'); const [muted, setMuted] = useState(true); const [error, setError] = useState('')
  const stream = useRef(null); const peers = useRef(new Map()); const after = useRef(0)
  const generation = useRef(0);
  const speakAllowed = useRef(false); speakAllowed.current = canSpeak;
  const iceServers = useRef([{ urls: 'stun:stun.l.google.com:19302' }]).current
  const makePeer = useCallback((uid, initiator = false) => { if (peers.current.has(uid)) return peers.current.get(uid); const pc = new RTCPeerConnection({ iceServers }); stream.current?.getTracks().forEach(t => pc.addTrack(t, stream.current)); pc.onicecandidate = e => e.candidate && sendSignal(user, roomId, uid, 'ice', e.candidate.toJSON()); pc.ontrack = e => { let audio = document.getElementById(`voice-${uid}`); if (!audio) { audio = document.createElement('audio'); audio.id = `voice-${uid}`; audio.autoplay = true; audio.dataset.pomodoroAudio = 'true'; document.body.appendChild(audio) } audio.muted = !speakAllowed.current || audio.dataset.locallyMuted === 'true'; audio.srcObject = e.streams[0] }; peers.current.set(uid, pc); if (initiator) pc.createOffer().then(o => pc.setLocalDescription(o).then(() => sendSignal(user, roomId, uid, 'offer', o))); return pc }, [roomId, user])
  const join = useCallback(async () => { if (!enabled || !speakAllowed.current || stream.current) return; const attempt = generation.current; try { setError(''); setStatus('connecting'); const acquired = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true }, video: false }); if (attempt !== generation.current) { acquired.getTracks().forEach(t => t.stop()); return } stream.current = acquired; stream.current.getAudioTracks().forEach(t => { t.enabled = false }); if (!speakAllowed.current) { stream.current.getTracks().forEach(t => t.stop()); stream.current = null; setStatus('idle'); return } setMuted(true); setStatus('connected'); members.filter(m => m.user_key !== user.uid).forEach(m => makePeer(m.user_key, user.uid < m.user_key)) } catch { setError('Mikrofon izni verilmedi veya cihaz bulunamadı.'); setStatus('error') } }, [enabled, makePeer, members, user])
  const leave = useCallback(() => { ++generation.current; stream.current?.getTracks().forEach(t => t.stop()); stream.current = null; peers.current.forEach(p => p.close()); peers.current.clear(); document.querySelectorAll('[data-pomodoro-audio]').forEach(a => a.remove()); setStatus('idle'); setMuted(true) }, [])
  const toggleMute = () => { const next = !speakAllowed.current || !muted; stream.current?.getAudioTracks().forEach(t => { t.enabled = !next }); setMuted(next) }
  useEffect(() => { if (status !== 'connected') return; const poll = async () => { try { const r = await getSignals(user, roomId, after.current); for (const s of r.data.items) { after.current = Math.max(after.current, s.id); const pc = makePeer(s.sender_uid); if (s.signal_type === 'offer') { await pc.setRemoteDescription(s.payload); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); await sendSignal(user, roomId, s.sender_uid, 'answer', answer) } else if (s.signal_type === 'answer') await pc.setRemoteDescription(s.payload); else if (s.signal_type === 'ice') await pc.addIceCandidate(s.payload) } } catch { /* next poll retries */ } }; poll(); const id = setInterval(poll, 1500); return () => clearInterval(id) }, [makePeer, roomId, status, user])
  useEffect(() => { if (!canSpeak) { stream.current?.getAudioTracks().forEach(t => { t.enabled = false }); setMuted(true); document.querySelectorAll('[data-pomodoro-audio]').forEach(a => { a.muted = true }) } else { document.querySelectorAll('[data-pomodoro-audio]').forEach(a => { a.muted = a.dataset.locallyMuted === 'true' }) } }, [canSpeak])
  useEffect(() => { if (!canSpeak) return; const id = setTimeout(() => { speakAllowed.current = false; stream.current?.getAudioTracks().forEach(t => { t.enabled = false }); setMuted(true); document.querySelectorAll('[data-pomodoro-audio]').forEach(a => { a.muted = true }) }, Math.max(0, muteAt - performance.now())); return () => clearTimeout(id) }, [canSpeak, muteAt])
  useEffect(() => { if (!enabled) leave() }, [enabled, leave])
  useEffect(() => leave, [leave, roomId])
  return { status, muted, error, join, leave, toggleMute }
}
