import { Headphones, LogOut, Mic, MicOff, Music, Pause, Play, Shield, SkipForward, UserX, Volume2, VolumeX } from 'lucide-react'
import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import Button from '../components/Button'
import Container from '../components/Container'
import UserAvatar from '../components/user/UserAvatar'
import { useAuth } from '../context/useAuth'
import { addMusic, getRoom, heartbeat, leaveRoom, moderate, musicAction, timerAction } from '../api/pomodoroApi'
import { canSpeakInRoom, formatTimer, roomSeconds, supportedMusicUrl } from '../utils/pomodoro'
import { usePomodoroVoice } from '../hooks/usePomodoroVoice'

function PomodoroRoomPage() {
  const { roomId } = useParams(); const { user } = useAuth(); const navigate = useNavigate()
  const receivedAt = useRef(0); const version = useRef(0); const active = useRef(true); const [now, setNow] = useState(() => performance.now()); const [busy, setBusy] = useState(false)
  const [room, setRoom] = useState(null); const [error, setError] = useState(''); const [musicUrl, setMusicUrl] = useState(''); const [localMuted, setLocalMuted] = useState({})
  const load = useCallback(async () => { const request = ++version.current; try { const r = await getRoom(user, roomId); if (!active.current || request !== version.current) return; receivedAt.current = performance.now(); setNow(receivedAt.current); setRoom(r.data.room); setError('') } catch (e) { if (active.current && request === version.current) setError(e.message) } }, [roomId, user])
  useEffect(() => { active.current = true; load(); const sync = setInterval(load, 3000); const tick = setInterval(() => setNow(performance.now()), 250); const visible = () => { if (!document.hidden) load() }; document.addEventListener('visibilitychange', visible); return () => { active.current = false; clearInterval(sync); clearInterval(tick); document.removeEventListener('visibilitychange', visible) } }, [load])
  const seconds = roomSeconds(room, now - receivedAt.current)
  const canSpeak = canSpeakInRoom(room, seconds, now - receivedAt.current < 10000)
  const voice = usePomodoroVoice({ user, roomId, members: room?.members || [], enabled: room?.voice_enabled, canSpeak, muteAt: Math.min(receivedAt.current + Number(room?.remaining_seconds || 0) * 1000, receivedAt.current + 10000) })
  const micEnabled = canSpeak && voice.status === 'connected' && !voice.muted
  const hasRoom = Boolean(room)
  useEffect(() => { if (!hasRoom) return; const beat = () => heartbeat(user, roomId, micEnabled).catch(() => {}); beat(); const id = setInterval(beat, 15000); return () => clearInterval(id) }, [hasRoom, micEnabled, roomId, user])
  async function timer(action, body) { if (busy) return; setBusy(true); ++version.current; try { await timerAction(user, roomId, action, body); await load() } catch (e) { setError(e.message) } finally { setBusy(false) } }
  async function leave() { voice.leave(); await leaveRoom(user, roomId).catch(() => {}); navigate('/pomodoro') }
  async function queue(event) { event.preventDefault(); if (!supportedMusicUrl(musicUrl)) return setError('Yalnızca YouTube ve Spotify bağlantıları desteklenir.'); try { await addMusic(user, roomId, musicUrl); setMusicUrl(''); await load() } catch (e) { setError(e.message) } }
  if (!room) return <section className="pomodoro-page"><Container>{error ? <div className="pomo-alert">{error}</div> : <p>Oda hazırlanıyor…</p>}<Button to="/pomodoro" variant="secondary">Odalara dön</Button></Container></section>
  const owner = room.is_owner
  const phase = room.current_phase
  const duration = (phase === 'break' || (phase === 'paused' && room.phase_before_pause === 'break') ? room.break_minutes : room.work_minutes) * 60
  const progress = Math.max(0, Math.min(100, 100 * (1 - seconds / duration)))
  return <section className="pomodoro-page room-page"><Container>
    <div className="room-heading"><div><span className="eyebrow">{room.category} · {room.visibility === 'private' ? 'ÖZEL ODA' : 'HERKESE AÇIK'}</span><h1>{room.name}</h1><p>{room.description}</p></div><Button icon={LogOut} variant="secondary" onClick={leave}>Odadan Çık</Button></div>{error && <div className="pomo-alert">{error}</div>}
    <div className="room-session-strip"><span>{room.member_count} / {room.max_members} kişi</span><span>{room.work_minutes} dk odak · {room.break_minutes} dk mola</span><span>Mikrofonlar yalnızca molada</span></div><div className="room-layout"><main className="timer-panel"><span className={`phase-badge phase--${room.current_phase}`}>{room.current_phase === 'work' ? 'Odaklanma zamanı' : room.current_phase === 'break' ? 'Mola zamanı' : room.current_phase === 'paused' ? 'Duraklatıldı' : 'Başlamaya hazır'}</span><div className="timer-clock" role="timer" aria-label="Kalan süre">{formatTimer(seconds)}</div><div className="timer-progress" role="progressbar" aria-label="Tur ilerlemesi" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)}><span style={{ width: `${progress}%` }}/></div><h2>{room.cycle_number}. Çalışma Turu</h2><p>{phase === 'idle' ? 'Hazır olduğunda başlayalım.' : phase === 'paused' ? 'Kalan süren saklandı.' : seconds === 0 ? 'Yeni aşama eşitleniyor…' : phase === 'break' ? 'Biraz dinlen. Sohbet etmek istersen mikrofonunu aç.' : 'Tek bir işe odaklan. Bu süre sana ait.'}</p>{owner && <div className="timer-controls"><Button disabled={busy} icon={room.current_phase === 'idle' || room.current_phase === 'paused' ? Play : Pause} onClick={() => timer(room.current_phase === 'idle' ? 'start' : room.current_phase === 'paused' ? 'resume' : 'pause')}>{room.current_phase === 'idle' ? 'Başlat' : room.current_phase === 'paused' ? 'Sürdür' : 'Duraklat'}</Button><Button disabled={busy} icon={SkipForward} variant="secondary" onClick={() => timer('next')}>{phase === 'work' || (phase === 'paused' && room.phase_before_pause === 'work') ? 'Molaya geç' : 'Çalışmaya geç'}</Button></div>}{owner && <form key={`${room.work_minutes}-${room.break_minutes}`} className="duration-controls" onSubmit={e => { e.preventDefault(); timer('durations', { work_minutes: +e.currentTarget.work.value, break_minutes: +e.currentTarget.break.value }) }}><label>Çalışma <input name="work" type="number" min="5" max="180" defaultValue={room.work_minutes}/></label><label>Mola <input name="break" type="number" min="1" max="60" defaultValue={room.break_minutes}/></label><button disabled={busy}>Süreleri kaydet</button></form>}</main>
      <section className="people-panel"><div className="panel-title"><div><span className="eyebrow">ÇALIŞMA ARKADAŞLARIN</span><h2>Birlikte daha kolay <span>({room.member_count})</span></h2></div><Shield size={18}/></div><div className="member-grid">{room.members.map(member => <div className="member-card" key={member.user_key}><UserAvatar size={64} profile={{ username: member.username }} profilePhotoUrl={member.profile_photo_url}/><div><strong>{member.username}{member.user_key === user.uid && <em> · Sen</em>}</strong><small>{member.role === 'owner' ? 'Host · ' : ''}{phase === 'break' ? 'Molada' : phase === 'work' ? 'Odaklanıyor' : phase === 'paused' ? 'Bekliyor' : 'Hazır'}</small></div><button title={localMuted[member.user_key] ? 'Sesini aç' : 'Kendi cihazımda sessize al'} onClick={() => { const audio = document.getElementById(`voice-${member.user_key}`); if (audio) { audio.dataset.locallyMuted = String(!localMuted[member.user_key]); audio.muted = !canSpeak || !localMuted[member.user_key] } setLocalMuted(v => ({...v,[member.user_key]:!v[member.user_key]})) }}>{localMuted[member.user_key] ? <VolumeX/> : (canSpeak && (member.user_key === user.uid ? micEnabled : member.microphone_enabled)) ? <Volume2/> : <MicOff/>}</button>{owner && member.role !== 'owner' && <button title="Odadan çıkar" onClick={() => moderate(user, roomId, 'kick', member.user_key).then(load)}><UserX/></button>}</div>)}</div>{room.voice_enabled && <div className="voice-box"><h3><Headphones size={18}/> Sesli sohbet</h3>{voice.status !== 'connected' ? <Button disabled={!canSpeak || voice.status === 'connecting'} icon={Mic} onClick={voice.join}>{voice.status === 'connecting' ? 'Bağlanıyor…' : canSpeak ? 'Sesliye katıl' : 'Molada açılır'}</Button> : <><Button disabled={!canSpeak} icon={voice.muted ? MicOff : Mic} onClick={voice.toggleMute}>{voice.muted ? 'Mikrofonu Aç' : 'Mikrofonu Kapat'}</Button><button className="text-button" onClick={voice.leave}>Sesliden çık</button></>}<small>{voice.error || (!canSpeak ? 'Mola dışında herkesin mikrofonu otomatik kapalı tutulur.' : 'Mola sohbeti açık. Mikrofonunu kendin açarsın; mola bitince kapanır.')}</small></div>}</section>
    </div>{room.music_enabled && <section className="music-panel"><div className="panel-title"><h2><Music size={20}/> Ortak müzik</h2>{owner && room.music_queue.length > 0 && <div><button onClick={() => musicAction(user, roomId, 'skip').then(load)}>Geç</button><button onClick={() => musicAction(user, roomId, 'clear').then(load)}>Temizle</button></div>}</div><p>Oynatmayı bağlantıyı açarak sen başlatırsın; ses düzeyi cihazına özeldir.</p><form onSubmit={queue}><input aria-label="YouTube veya Spotify bağlantısı" placeholder="YouTube veya Spotify bağlantısı" value={musicUrl} onChange={e => setMusicUrl(e.target.value)}/><Button type="submit">Sıraya Ekle</Button></form><ol>{room.music_queue.map((track, i) => <li key={track.id}><span>{i === 0 ? 'Şimdi' : i + 1}</span><a href={track.external_url} target="_blank" rel="noreferrer">{track.title || `${track.provider} parçası`}</a><small>{track.added_by}</small></li>)}</ol></section>}
  </Container></section>
}
export default PomodoroRoomPage
