import { Headphones, LogOut, Mic, MicOff, Music, Pause, Play, Shield, SkipForward, UserX, Volume2, VolumeX } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import Button from '../components/Button'
import Container from '../components/Container'
import UserAvatar from '../components/user/UserAvatar'
import { useAuth } from '../context/useAuth'
import { addMusic, getRoom, heartbeat, leaveRoom, moderate, musicAction, timerAction } from '../api/pomodoroApi'
import { formatTimer, remainingSeconds, supportedMusicUrl } from '../utils/pomodoro'
import { usePomodoroVoice } from '../hooks/usePomodoroVoice'

function PomodoroRoomPage() {
  const { roomId } = useParams(); const { user } = useAuth(); const navigate = useNavigate()
  const [room, setRoom] = useState(null); const [error, setError] = useState(''); const [seconds, setSeconds] = useState(0); const [musicUrl, setMusicUrl] = useState(''); const [localMuted, setLocalMuted] = useState({})
  const load = useCallback(async () => { try { const r = await getRoom(user, roomId); setRoom(r.data.room); setSeconds(remainingSeconds(r.data.room.phase_ends_at, r.data.server_now)); setError('') } catch (e) { setError(e.message) } }, [roomId, user])
  useEffect(() => { load(); const sync = setInterval(load, 10000); const beat = setInterval(() => heartbeat(user, roomId).catch(() => {}), 15000); return () => { clearInterval(sync); clearInterval(beat) } }, [load, roomId, user])
  useEffect(() => { const id = setInterval(() => setSeconds(v => Math.max(0, v - 1)), 1000); return () => clearInterval(id) }, [])
  const voice = usePomodoroVoice({ user, roomId, members: room?.members || [], enabled: room?.voice_enabled })
  async function timer(action, body) { try { await timerAction(user, roomId, action, body); await load() } catch (e) { setError(e.message) } }
  async function leave() { await leaveRoom(user, roomId).catch(() => {}); voice.leave(); navigate('/pomodoro') }
  async function queue(event) { event.preventDefault(); if (!supportedMusicUrl(musicUrl)) return setError('Yalnızca YouTube ve Spotify bağlantıları desteklenir.'); try { await addMusic(user, roomId, musicUrl); setMusicUrl(''); await load() } catch (e) { setError(e.message) } }
  if (!room) return <section className="pomodoro-page"><Container>{error ? <div className="pomo-alert">{error}</div> : <p>Oda hazırlanıyor…</p>}<Button to="/pomodoro" variant="secondary">Odalara dön</Button></Container></section>
  const owner = room.is_owner
  return <section className="pomodoro-page room-page"><Container>
    <div className="room-heading"><div><span className="eyebrow">{room.category} · {room.visibility === 'private' ? 'ÖZEL ODA' : 'HERKESE AÇIK'}</span><h1>{room.name}</h1><p>{room.description}</p></div><Button icon={LogOut} variant="secondary" onClick={leave}>Odadan Çık</Button></div>{error && <div className="pomo-alert">{error}</div>}
    <div className="room-layout"><main className="timer-panel"><span className={`phase-badge phase--${room.current_phase}`}>{room.current_phase === 'work' ? 'Odaklanma zamanı' : room.current_phase === 'break' ? 'Mola zamanı' : room.current_phase === 'paused' ? 'Duraklatıldı' : 'Başlamaya hazır'}</span><div className="timer-clock" aria-live="polite">{formatTimer(seconds)}</div><h2>{room.cycle_number}. Çalışma Turu</h2><p>{room.member_count} kişi şu anda {room.current_phase === 'break' ? 'mola veriyor' : 'çalışıyor'}</p>{owner && <div className="timer-controls"><Button icon={room.current_phase === 'idle' || room.current_phase === 'paused' ? Play : Pause} onClick={() => timer(room.current_phase === 'idle' ? 'start' : room.current_phase === 'paused' ? 'resume' : 'pause')}>{room.current_phase === 'idle' ? 'Başlat' : room.current_phase === 'paused' ? 'Sürdür' : 'Duraklat'}</Button><Button icon={SkipForward} variant="secondary" onClick={() => timer('next')}>Sonraki Tur</Button></div>}{owner && <form className="duration-controls" onSubmit={e => { e.preventDefault(); timer('durations', { work_minutes: +e.currentTarget.work.value, break_minutes: +e.currentTarget.break.value }) }}><label>Çalışma <input name="work" type="number" min="5" max="180" defaultValue={room.work_minutes}/></label><label>Mola <input name="break" type="number" min="1" max="60" defaultValue={room.break_minutes}/></label><button>Güncelle</button></form>}</main>
      <aside className="people-panel"><div className="panel-title"><h2>Odada ({room.member_count})</h2><Shield size={18}/></div><div className="member-list">{room.members.map(member => <div className="member" key={member.user_key}><UserAvatar profile={{ username: member.username }} profilePhotoUrl={member.profile_photo_url}/><div><strong>{member.username}</strong><small>{member.role === 'owner' ? 'Host · ' : ''}{room.current_phase === 'break' ? 'Molada' : 'Çalışıyor'}</small></div><button title={localMuted[member.user_key] ? 'Sesini aç' : 'Kendi cihazımda sessize al'} onClick={() => { const audio = document.getElementById(`voice-${member.user_key}`); if (audio) audio.muted = !audio.muted; setLocalMuted(v => ({...v,[member.user_key]:!v[member.user_key]})) }}>{localMuted[member.user_key] ? <VolumeX/> : member.microphone_enabled ? <Volume2/> : <MicOff/>}</button>{owner && member.role !== 'owner' && <button title="Odadan çıkar" onClick={() => moderate(user, roomId, 'kick', member.user_key).then(load)}><UserX/></button>}</div>)}</div>{room.voice_enabled && <div className="voice-box"><h3><Headphones size={18}/> Sesli sohbet</h3>{voice.status === 'idle' ? <Button icon={Mic} onClick={voice.join}>Sesliye Katıl</Button> : <><Button icon={voice.muted ? MicOff : Mic} onClick={voice.toggleMute}>{voice.muted ? 'Mikrofonu Aç' : 'Mikrofonu Kapat'}</Button><button className="text-button" onClick={voice.leave}>Sesliden çık</button></>}<small>{voice.error || (voice.status === 'connected' ? 'Bağlı · Görüşmeler kaydedilmez.' : 'Mikrofon varsayılan olarak kapalıdır. Görüşmeler kaydedilmez.')}</small></div>}</aside>
    </div>{room.music_enabled && <section className="music-panel"><div className="panel-title"><h2><Music size={20}/> Ortak müzik</h2>{owner && room.music_queue.length > 0 && <div><button onClick={() => musicAction(user, roomId, 'skip').then(load)}>Geç</button><button onClick={() => musicAction(user, roomId, 'clear').then(load)}>Temizle</button></div>}</div><p>Oynatmayı bağlantıyı açarak sen başlatırsın; ses düzeyi cihazına özeldir.</p><form onSubmit={queue}><input aria-label="YouTube veya Spotify bağlantısı" placeholder="YouTube veya Spotify bağlantısı" value={musicUrl} onChange={e => setMusicUrl(e.target.value)}/><Button type="submit">Sıraya Ekle</Button></form><ol>{room.music_queue.map((track, i) => <li key={track.id}><span>{i === 0 ? 'Şimdi' : i + 1}</span><a href={track.external_url} target="_blank" rel="noreferrer">{track.title || `${track.provider} parçası`}</a><small>{track.added_by}</small></li>)}</ol></section>}
  </Container></section>
}
export default PomodoroRoomPage
