SET @profile_columns = 'first_name,last_name,birth_year,bio,education_status,school_name,graduated_high_school,university,department,grade_level,city,profile_photo_path,profile_visibility,email_public,birth_year_public';

SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'first_name') = 0, 'ALTER TABLE user_profiles ADD COLUMN first_name VARCHAR(80) NOT NULL DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'last_name') = 0, 'ALTER TABLE user_profiles ADD COLUMN last_name VARCHAR(80) NOT NULL DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'birth_year') = 0, 'ALTER TABLE user_profiles ADD COLUMN birth_year SMALLINT UNSIGNED NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'bio') = 0, 'ALTER TABLE user_profiles ADD COLUMN bio VARCHAR(300) NOT NULL DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'education_status') = 0, 'ALTER TABLE user_profiles ADD COLUMN education_status ENUM(''ortaokul'',''lise'',''universite'',''mezun'') NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'school_name') = 0, 'ALTER TABLE user_profiles ADD COLUMN school_name VARCHAR(180) NOT NULL DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'graduated_high_school') = 0, 'ALTER TABLE user_profiles ADD COLUMN graduated_high_school VARCHAR(180) NOT NULL DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'university') = 0, 'ALTER TABLE user_profiles ADD COLUMN university VARCHAR(180) NOT NULL DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'department') = 0, 'ALTER TABLE user_profiles ADD COLUMN department VARCHAR(180) NOT NULL DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'grade_level') = 0, 'ALTER TABLE user_profiles ADD COLUMN grade_level VARCHAR(40) NOT NULL DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'city') = 0, 'ALTER TABLE user_profiles ADD COLUMN city VARCHAR(100) NOT NULL DEFAULT ''''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'profile_photo_path') = 0, 'ALTER TABLE user_profiles ADD COLUMN profile_photo_path VARCHAR(255) NULL', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'profile_visibility') = 0, 'ALTER TABLE user_profiles ADD COLUMN profile_visibility ENUM(''public'',''private'') NOT NULL DEFAULT ''private''', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'email_public') = 0, 'ALTER TABLE user_profiles ADD COLUMN email_public TINYINT(1) NOT NULL DEFAULT 0', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'user_profiles' AND column_name = 'birth_year_public') = 0, 'ALTER TABLE user_profiles ADD COLUMN birth_year_public TINYINT(1) NOT NULL DEFAULT 0', 'SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
